using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

public partial class maintgrid : System.Web.UI.Page
{
    SqlDataAdapter da;
    SqlConnection cn;
    SqlCommand cmd;
    DataTable dt;
    DataSet ds;
    protected void Page_Load(object sender, EventArgs e)
    {
        cn = new SqlConnection(@"Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\fam.mdf;Integrated Security=True;User Instance=True");
        if (!IsPostBack)
        {
            fill();
        }
    }
    public void connection()
    {
        cn.Open();
        cmd.ExecuteNonQuery();
        cn.Close();
    }
    public void fill()
    {
        da = new SqlDataAdapter("select * from maintanance", cn);
        dt = new DataTable();
        da.Fill(dt);
        if (dt.Rows.Count > 0)
        {
            GridView1.DataSource = dt;
            GridView1.DataBind();
        }
        else
        {
            dt = new DataTable();
            DataColumn dc1 = new DataColumn("maintananceid", typeof(string));
            DataColumn dc2 = new DataColumn("cost", typeof(string));
            DataColumn dc3 = new DataColumn("date", typeof(string));
            DataColumn dc4 = new DataColumn("assetid", typeof(string));
            DataColumn dc5 = new DataColumn("maintananceby", typeof(string));
            dt.Columns.Add(dc1);
            dt.Columns.Add(dc2);
            dt.Columns.Add(dc3);
            dt.Columns.Add(dc4);
            dt.Columns.Add(dc5);
            DataRow dr = dt.NewRow();
            dr["maintananceid"] = "No Record";
            dr["cost"] = "No Record";
            dr["date"] = "No Record";
            dr["assetid"] = "No Record";
            dr["maintananceby"] = "No Record";
            dt.Rows.Add(dr);
            GridView1.DataSource = dt;
            GridView1.DataBind();

        }

    }


    protected void GridView1_RowUpdating(object sender, GridViewUpdateEventArgs e)
    {
        Label lblid1 = (Label)GridView1.Rows[e.RowIndex].FindControl("Label8");
       TextBox txtcost = (TextBox)GridView1.Rows[e.RowIndex].FindControl("Textbox1");
        TextBox txtdate = (TextBox)GridView1.Rows[e.RowIndex].FindControl("Textbox2");
        TextBox txtassetid = (TextBox)GridView1.Rows[e.RowIndex].FindControl("Textbox3");
        TextBox txmby = (TextBox)GridView1.Rows[e.RowIndex].FindControl("Textbox4");

        cmd = new SqlCommand("update maintanance set cost=@cost,date=@date,assetid=@assetid,maintananceby=@maintananceby where maintananceid=@maintananceid", cn);
        cmd.Parameters.AddWithValue("@maintananceid",lblid1.Text);
        cmd.Parameters.AddWithValue("@cost", txtcost.Text);
        cmd.Parameters.AddWithValue("@date", txtdate.Text);
        cmd.Parameters.AddWithValue("@assetid", txtassetid.Text);
        cmd.Parameters.AddWithValue("@maintananceby", txmby.Text);
      
        connection();
        GridView1.EditIndex = -1;
        fill();
        Label7.Text = "Updated Successfully";



    }
    protected void GridView1_RowEditing(object sender, GridViewEditEventArgs e)
    {
        GridView1.EditIndex = e.NewEditIndex;
        fill();
    }
    protected void GridView1_RowCancelingEdit(object sender, GridViewCancelEditEventArgs e)
    {
        GridView1.EditIndex = -1;
        fill();
    }
    protected void Button2_Click(object sender, EventArgs e)
    {
        da = new SqlDataAdapter("select * from maintanance", cn);
        dt = new DataTable();
        da.Fill(dt);
    
        for (int i = 0; i < dt.Rows.Count; i++)
        {
            LinkButton lnk = (LinkButton)GridView1.Rows[i].FindControl("LinkButton123");
            lnk.Visible = true;

        }
    }
    protected void Button3_Click(object sender, EventArgs e)
    { da = new SqlDataAdapter("select * from maintanance ", cn);
        dt = new DataTable();
        da.Fill(dt);

        for (int i = 0; i < dt.Rows.Count; i++)
        {
            CheckBox chk = (CheckBox)GridView1.Rows[i].FindControl("CheckBox1");
            if (chk.Checked == true)
            {
                Label lbl = (Label)GridView1.Rows[i].FindControl("Label1");
                cmd = new SqlCommand("delete from maintanance where maintananceid=@id", cn);
                cmd.Parameters.AddWithValue("@id", lbl.Text);
                connection();
            }
        }
       
        fill();
        Label7.Text = "Deleted Successfully";
        //GridView1.AutoGenerateDeleteButton = true;
    }
    protected void GridView1_RowDeleting(object sender, GridViewDeleteEventArgs e)
    {
        Label lblid = (Label)GridView1.Rows[e.RowIndex].FindControl("Label1");
        cmd = new SqlCommand("delete from maintanance where maintananceid=@maintananceid", cn);
        cmd.Parameters.AddWithValue("@maintananceid", lblid.Text);
        connection();
        Label7.Text = "Deleted Successfully";
        fill();

    }
    protected void CheckBox2_CheckedChanged(object sender, EventArgs e)
    {
        CheckBox chk1 = (CheckBox)GridView1.HeaderRow.FindControl("CheckBox2");
        da = new SqlDataAdapter("select * from maintanance ", cn);
        dt = new DataTable();
        da.Fill(dt);
        for (int i = 0; i < dt.Rows.Count; i++)
        {
            CheckBox chk = (CheckBox)GridView1.Rows[i].FindControl("CheckBox1");
            if (chk1.Checked == true)
            {
                chk.Checked = true;
            }
            else
            {
                chk.Checked = false;
            }
        }
    }
}